%=============================================================================
% Copyright (c) 2016-present Allan CORNET (Nelson)
%=============================================================================
% This file is part of Nelson.
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
% uihtml: a page and Nelson exchanging values in both directions.
%
% The page owns the interface, Nelson owns the computation. Moving the slider
% sends an event to Nelson, Nelson converts and writes Data back, and the page
% redraws from what it receives. Neither side polls the other.
%=============================================================================
if ~strcmp(getnelsonmode(), 'WEB_GUI')
  error('Nelson:uihtml:webviewDesktopRequired', ...
    _('uihtml is supported only in the WebView desktop. See help uihtml.'));
end
%=============================================================================
page = strjoin({...
  '<html><head><meta charset="utf-8"><style>', ...
  'body { font: 14px system-ui; margin: 12px; color: #222; }', ...
  'h3 { margin: 0 0 12px 0; font-size: 15px; }', ...
  'input { width: 100%; }', ...
  '.row { display: flex; gap: 18px; margin-top: 14px; }', ...
  '.cell { flex: 1; background: #f4f6f8; border-radius: 6px; padding: 10px; }', ...
  '.cell b { display: block; font-size: 22px; margin-top: 4px; }', ...
  '.hint { color: #666; font-size: 12px; margin-top: 14px; }', ...
  '</style></head><body>', ...
  '<h3>Celsius to Fahrenheit and Kelvin</h3>', ...
  '<input id="slider" type="range" min="-40" max="120" value="20">', ...
  '<div class="row">', ...
  '  <div class="cell">Celsius<b id="c">--</b></div>', ...
  '  <div class="cell">Fahrenheit<b id="f">--</b></div>', ...
  '  <div class="cell">Kelvin<b id="k">--</b></div>', ...
  '</div>', ...
  '<p class="hint">The page sends the slider value; Nelson converts it and', ...
  ' writes the result back into Data.</p>', ...
  '<script>', ...
  'function setup(htmlComponent) {', ...
  '  var slider = document.getElementById("slider");', ...
  '  slider.addEventListener("input", function () {', ...
  '    htmlComponent.sendEventToNelson("celsius", { value: Number(slider.value) });', ...
  '  });', ...
  '  htmlComponent.addEventListener("DataChanged", function () {', ...
  '    var d = htmlComponent.Data;', ...
  '    if (!d) { return; }', ...
  '    document.getElementById("c").textContent = d.celsius.toFixed(1);', ...
  '    document.getElementById("f").textContent = d.fahrenheit.toFixed(1);', ...
  '    document.getElementById("k").textContent = d.kelvin.toFixed(2);', ...
  '  });', ...
  '  htmlComponent.sendEventToNelson("celsius", { value: Number(slider.value) });', ...
  '}', ...
  '</script></body></html>'}, '');
%=============================================================================
f = uifigure('Name', 'uihtml unit converter', 'Position', [200 200 520 320]);
h = uihtml(f, 'Position', [10 10 500 300], 'HTMLSource', page);
% The page asks, Nelson answers: the callback writes Data, which the page then
% receives as a DataChanged event. A Nelson write never re-notifies Nelson.
h.HTMLEventReceivedFcn = @(src, event) set(src, 'Data', ...
  struct('celsius', event.HTMLEventData.value, ...
         'fahrenheit', event.HTMLEventData.value * 9 / 5 + 32, ...
         'kelvin', event.HTMLEventData.value + 273.15));
%=============================================================================
