%=============================================================================
% Copyright (c) 2016-present Allan CORNET (Nelson)
%=============================================================================
% This file is part of Nelson.
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
function uihtml_wave_packet()
  % A quantum wave packet in a potential well you shape with the mouse.
  %
  % The division of labour is the point. Nelson diagonalises the Hamiltonian
  % once per shape change; the page then animates forever at 60 frames per
  % second without asking Nelson for anything, because once you own the
  % spectrum the time evolution is a closed-form phase rotation rather than a
  % stepped integration. Nothing here is recomputed per frame.
  %
  % It also runs straight into the one rule that bites everybody: complex
  % values cannot cross to the page. The expansion coefficients are split into
  % their real and imaginary parts and the phase is rebuilt in JavaScript.
  if ~strcmp(getnelsonmode(), 'WEB_GUI')
    error('Nelson:uihtml:webviewDesktopRequired', ...
      _('uihtml is supported only in the WebView desktop. See help uihtml.'));
  end
  f = uifigure('Name', 'uihtml: wave packet', 'Position', [120 120 940 560]);
  h = uihtml(f, 'Position', [10 10 920 540], 'HTMLSource', wavePacketPage());
  h.UserData = struct('ready', false);
  % The page asks for its state once it has loaded; answering an explicit
  % request avoids racing the page's own startup.
  h.HTMLEventReceivedFcn = @wavePacketEvent;
end
%=============================================================================
function wavePacketEvent(src, event)
  name = event.HTMLEventName;
  payload = event.HTMLEventData;
  switch name
    case 'ready'
      wavePacketSetPotential(src, [0.0 0.0 1.0 0.0 0.0]);
    case 'potential'
      wavePacketSetPotential(src, payload.heights(:)');
    case 'launch'
      wavePacketLaunch(src, payload.x0, payload.k0);
    case 'eigenstate'
      wavePacketEigenstate(src, payload.n);
  end
end
%=============================================================================
function wavePacketSetPotential(src, heights)
  [x, V, E, Phi, dx] = wavePacketBasis(heights);
  state = struct('x', x, 'V', V, 'E', E, 'Phi', Phi, 'dx', dx, 'heights', heights);
  src.UserData = state;
  % Data is the component's state, not a message queue: two writes in one
  % callback leave only the second, so the basis and the packet travel together.
  wavePacketLaunch(src, 0.25, 60);
end
%=============================================================================
function wavePacketLaunch(src, x0, k0)
  state = src.UserData;
  if ~isfield(state, 'Phi')
    return
  end
  x = state.x;
  sigma = 0.045;
  psi = exp(-((x - x0) .^ 2) / (4 * sigma ^ 2)) .* exp(1i * k0 * x);
  psi = psi / sqrt(sum(abs(psi) .^ 2) * state.dx);
  c = (state.Phi' * psi) * state.dx;
  weights = abs(c) .^ 2;
  % Honesty about truncation: with a finite number of modes the packet is not
  % fully represented, and the residual says by how much.
  residual = max(0, 1 - sum(weights));
  meanE = sum(weights .* state.E);
  spread = sqrt(max(0, sum(weights .* state.E .^ 2) - meanE ^ 2));
  % The animation clock comes from the packet's own energy spread, never from a
  % level difference: a symmetric well makes its two lowest levels degenerate to
  % machine precision, and a clock based on that gap runs at 1e-10 and freezes
  % the picture. The spread is what actually governs the visible motion.
  % Complex values cannot cross the bridge, so the coefficients travel as two
  % real arrays and the page rebuilds the phase itself.
  wavePacketPublish(src, c, meanE, spread, residual);
  if residual > 0.02
    sendEventToHTMLSource(src, 'notice', ...
      struct('text', 'Packet too narrow or too fast for the retained modes.'));
  end
end
%=============================================================================
function wavePacketEigenstate(src, n)
  state = src.UserData;
  if ~isfield(state, 'Phi')
    return
  end
  modes = numel(state.E);
  n = max(1, min(modes, round(n)));
  c = zeros(modes, 1);
  c(n) = 1;
  wavePacketPublish(src, c, state.E(n), 0, 0);
end
%=============================================================================
function wavePacketPublish(src, c, meanE, spread, residual)
  % One value carrying the whole state: the spectrum the page animates from and
  % the coefficients of the packet currently on it.
  state = src.UserData;
  src.Data = struct('x', state.x(:)', 'V', state.V(:)', 'E', state.E(:)', ...
    'phi', state.Phi(:)', 'n', numel(state.x), 'modes', numel(state.E), ...
    'heights', state.heights, ...
    'cre', real(c(:))', 'cim', imag(c(:))', ...
    'meanE', meanE, 'spread', spread, 'residual', residual);
end
%=============================================================================
function [x, V, E, Phi, dx] = wavePacketBasis(heights)
  % Units hbar = m = 1 on a box of unit width with hard walls.
  N = 220;
  dx = 1 / (N + 1);
  x = (1:N)' * dx;
  V = wavePacketPotential(x, heights);
  e = ones(N, 1);
  H = full(spdiags([-e, 2 * e, -e], -1:1, N, N)) / (2 * dx ^ 2) + diag(V);
  [vectors, values] = eig(H);
  [E, order] = sort(diag(values));
  vectors = vectors(:, order);
  modes = 40;
  E = E(1:modes);
  Phi = vectors(:, 1:modes);
  for k = 1:modes
    v = Phi(:, k) / sqrt(sum(Phi(:, k) .^ 2) * dx);
    % eig is free to return either sign. Pin it, or the picture flips every
    % time the basis is rebuilt.
    [~, peak] = max(abs(v));
    if v(peak) < 0
      v = -v;
    end
    Phi(:, k) = v;
  end
end
%=============================================================================
function V = wavePacketPotential(x, heights)
  % Five control points, smoothly interpolated, scaled so that a height of one
  % is a barrier the low modes can tunnel through but not ignore.
  nodes = linspace(0, 1, numel(heights));
  V = interp1(nodes, heights(:)', x(:)', 'spline')' * 2500;
  V = max(V, 0);
end
%=============================================================================
function page = wavePacketPage()
  page = strjoin({...
    '<html><head><meta charset="utf-8"><style>', ...
    ':root { color-scheme: dark; }', ...
    'body { margin:0; background:#05070d; color:#c9d4e6;', ...
    '  font:13px/1.45 ui-sans-serif,system-ui,sans-serif; overflow:hidden; }', ...
    '.wrap { display:flex; height:100vh; }', ...
    '.stage { position:relative; flex:1; }', ...
    'canvas { position:absolute; inset:0; width:100%; height:100%; }', ...
    'svg { position:absolute; inset:0; width:100%; height:100%; }', ...
    '.grab { fill:#7fe3ff; cursor:ns-resize; }', ...
    '.grab:hover { fill:#fff; }', ...
    '.side { width:250px; padding:14px 16px; background:#080b14;', ...
    '  border-left:1px solid #16203a; display:flex; flex-direction:column; }', ...
    'h1 { font-size:13px; letter-spacing:.14em; text-transform:uppercase;', ...
    '  color:#7c8db0; margin:0 0 12px 0; font-weight:600; }', ...
    '.read { display:flex; justify-content:space-between; padding:3px 0;', ...
    '  border-bottom:1px solid #101a2e; font-variant-numeric:tabular-nums; }', ...
    '.read b { color:#eaf2ff; font-weight:600; }', ...
    '.ladder { margin-top:12px; overflow:auto; flex:1; }', ...
    '.lvl { display:flex; align-items:center; gap:6px; height:13px; cursor:pointer; }', ...
    '.lvl:hover .bar { outline:1px solid #7fe3ff; }', ...
    '.lvl i { width:22px; color:#54658a; font-style:normal; font-size:11px;', ...
    '  text-align:right; }', ...
    '.bar { height:7px; border-radius:2px; background:#1d2a48; flex:1; }', ...
    '.bar span { display:block; height:100%; border-radius:2px;', ...
    '  background:linear-gradient(90deg,#2f7fff,#7fe3ff); }', ...
    '.hint { margin-top:10px; color:#5b6b8e; font-size:11px; }', ...
    '#toast { position:absolute; left:12px; bottom:12px; padding:6px 10px;', ...
    '  background:#20304f; border-radius:4px; opacity:0; transition:opacity .3s; }', ...
    '</style></head><body><div class="wrap">', ...
    '<div class="stage"><canvas id="cv"></canvas>', ...
    '<svg id="handles"></svg><div id="toast"></div></div>', ...
    '<div class="side"><h1>Wave packet</h1>', ...
    '<div class="read"><span>mean energy</span><b id="me">--</b></div>', ...
    '<div class="read"><span>spread</span><b id="sp">--</b></div>', ...
    '<div class="read"><span>truncation</span><b id="rs">--</b></div>', ...
    '<div class="read"><span>time scale</span><b id="bt">--</b></div>', ...
    '<div class="ladder" id="ladder"></div>', ...
    '<div class="hint">Drag the cyan handles to reshape the well.', ...
    ' Click and drag on the stage to launch a packet: sideways is momentum.', ...
    ' Click a level to see a stationary state.</div>', ...
    '</div></div><script>', ...
    wavePacketScript(), ...
    '</script></body></html>'}, '');
end
%=============================================================================
function script = wavePacketScript()
  script = strjoin({...
    'function setup(htmlComponent) {', ...
    '  var cv = document.getElementById("cv"), ctx = cv.getContext("2d");', ...
    '  var svg = document.getElementById("handles"), toast = document.getElementById("toast");', ...
    '  var st = null, cre = null, cim = null, t = 0, last = 0, dragging = null, aim = null;', ...
    '  var rate = 0.004;', ...
    '  var hue = new Array(721);', ...
    '  for (var i = 0; i <= 720; i++) { hue[i] = "hsl(" + (i / 2) + ",100%,60%)"; }', ...
    '  function size() { cv.width = cv.clientWidth; cv.height = cv.clientHeight; }', ...
    '  window.addEventListener("resize", size); size();', ...
    '  function px(v) { return v * cv.width; }', ...
    '  function py(v) { return cv.height * (0.62 - v); }', ...
    % Rebuild the interactive handles from the potential the engine sent back.
    '  function drawHandles() {', ...
    '    if (!st) { return; }', ...
    '    var s = "";', ...
    '    for (var k = 0; k < st.heights.length; k++) {', ...
    '      var hx = (k / (st.heights.length - 1)) * cv.width;', ...
    '      var hy = py(st.heights[k] * 0.16 + 0.02);', ...
    '      s += "<circle class=\"grab\" data-k=\"" + k + "\" cx=\"" + hx +', ...
    '        "\" cy=\"" + hy + "\" r=\"7\"></circle>";', ...
    '    }', ...
    '    svg.innerHTML = s;', ...
    '  }', ...
    '  function ladder() {', ...
    '    if (!st || !cre) { return; }', ...
    '    var s = "";', ...
    '    for (var n = 0; n < st.modes; n++) {', ...
    '      var w = (cre[n] * cre[n] + cim[n] * cim[n]) * 100;', ...
    '      s += "<div class=\"lvl\" data-n=\"" + n + "\"><i>" + (n + 1) +', ...
    '        "</i><div class=\"bar\"><span style=\"width:" +', ...
    '        Math.min(100, w) + "%\"></span></div></div>";', ...
    '    }', ...
    '    document.getElementById("ladder").innerHTML = s;', ...
    '  }', ...
    '  function frame(now) {', ...
    '    requestAnimationFrame(frame);', ...
    '    if (!st || !cre) { return; }', ...
    % Wall-clock driven: a slow machine drops frames but shows the same physics.
    '    var dt = last ? Math.min(0.05, (now - last) / 1000) : 0; last = now;', ...
    '    t += dt * rate;', ...
    '    ctx.globalCompositeOperation = "source-over";', ...
    '    ctx.fillStyle = "rgba(5,7,13,0.22)";', ...
    '    ctx.fillRect(0, 0, cv.width, cv.height);', ...
    '    ctx.strokeStyle = "#16203a"; ctx.lineWidth = 1;', ...
    '    ctx.beginPath();', ...
    '    for (var i = 0; i < st.n; i++) {', ...
    '      var vy = py(Math.min(0.42, st.V[i] / 6000) + 0.02);', ...
    '      if (i === 0) { ctx.moveTo(px(st.x[i]), vy); } else { ctx.lineTo(px(st.x[i]), vy); }', ...
    '    }', ...
    '    ctx.stroke();', ...
    '    ctx.globalCompositeOperation = "lighter";', ...
    '    for (var i2 = 0; i2 < st.n; i2++) {', ...
    '      var re = 0, im = 0;', ...
    '      for (var n2 = 0; n2 < st.modes; n2++) {', ...
    '        var ph = -st.E[n2] * t, cs = Math.cos(ph), sn = Math.sin(ph);', ...
    '        var ar = cre[n2] * cs - cim[n2] * sn, ai = cre[n2] * sn + cim[n2] * cs;', ...
    '        var p = st.phi[n2 * st.n + i2];', ...
    '        re += ar * p; im += ai * p;', ...
    '      }', ...
    '      var d = re * re + im * im;', ...
    '      if (d < 1e-4) { continue; }', ...
    '      var a = Math.atan2(im, re) + Math.PI;', ...
    '      ctx.fillStyle = hue[Math.round(a * 114.6)];', ...
    '      ctx.globalAlpha = Math.min(1, d * 0.55);', ...
    '      var hgt = Math.min(cv.height * 0.5, d * cv.height * 0.35);', ...
    '      ctx.fillRect(px(st.x[i2]) - 1, py(0.02) - hgt, 3, hgt);', ...
    '    }', ...
    '    ctx.globalAlpha = 1;', ...
    '    if (aim) {', ...
    '      ctx.globalCompositeOperation = "source-over";', ...
    '      ctx.strokeStyle = "#7fe3ff"; ctx.lineWidth = 2;', ...
    '      ctx.beginPath(); ctx.moveTo(aim.x, aim.y); ctx.lineTo(aim.cx, aim.y); ctx.stroke();', ...
    '    }', ...
    '  }', ...
    '  requestAnimationFrame(frame);', ...
    % Data is the state, not a message: adopting it has to work whether it
    % arrived as a change or was already there when the page opened.
    '  function adopt(d) {', ...
    '    if (!d || !d.phi) { return; }', ...
    '    st = d; cre = d.cre; cim = d.cim; t = 0;', ...
    '    rate = 3 / Math.max(1, d.spread);', ...
    '    drawHandles(); ladder();', ...
    '    document.getElementById("me").textContent = d.meanE.toFixed(1);', ...
    '    document.getElementById("sp").textContent = d.spread.toFixed(1);', ...
    '    document.getElementById("rs").textContent = (d.residual * 100).toFixed(1) + " %";', ...
    '    document.getElementById("bt").textContent = rate.toExponential(2);', ...
    '  }', ...
    % The engine answers a request: a new basis, or new coefficients.
    '  htmlComponent.addEventListener("DataChanged", function () {', ...
    '    adopt(htmlComponent.Data);', ...
    '  });', ...
    '  htmlComponent.addEventListener("notice", function (e) {', ...
    '    toast.textContent = e.Data.text; toast.style.opacity = 1;', ...
    '    setTimeout(function () { toast.style.opacity = 0; }, 2200);', ...
    '  });', ...
    % Reshaping the well: only the release asks Nelson to diagonalise again.
    '  svg.addEventListener("pointerdown", function (e) {', ...
    '    var k = e.target.getAttribute && e.target.getAttribute("data-k");', ...
    '    if (k !== null && k !== undefined) { dragging = Number(k); }', ...
    '  });', ...
    '  window.addEventListener("pointermove", function (e) {', ...
    '    if (dragging === null || !st) { return; }', ...
    '    var r = cv.getBoundingClientRect();', ...
    '    var v = (0.62 - (e.clientY - r.top) / r.height - 0.02) / 0.16;', ...
    '    st.heights[dragging] = Math.max(0, Math.min(2.5, v));', ...
    '    drawHandles();', ...
    '  });', ...
    '  window.addEventListener("pointerup", function () {', ...
    '    if (dragging !== null && st) {', ...
    '      htmlComponent.sendEventToNelson("potential", { heights: st.heights });', ...
    '    }', ...
    '    dragging = null;', ...
    '    if (aim && st) {', ...
    '      var dxp = (aim.cx - aim.x) / cv.width;', ...
    '      htmlComponent.sendEventToNelson("launch",', ...
    '        { x0: aim.x / cv.width, k0: dxp * 320 });', ...
    '      aim = null;', ...
    '    }', ...
    '  });', ...
    '  cv.addEventListener("pointerdown", function (e) {', ...
    '    var r = cv.getBoundingClientRect();', ...
    '    aim = { x: e.clientX - r.left, y: e.clientY - r.top, cx: e.clientX - r.left };', ...
    '  });', ...
    '  cv.addEventListener("pointermove", function (e) {', ...
    '    if (aim) { aim.cx = e.clientX - cv.getBoundingClientRect().left; }', ...
    '  });', ...
    '  document.getElementById("ladder").addEventListener("click", function (e) {', ...
    '    var row = e.target.closest && e.target.closest(".lvl");', ...
    '    if (row) {', ...
    '      htmlComponent.sendEventToNelson("eigenstate",', ...
    '        { n: Number(row.getAttribute("data-n")) + 1 });', ...
    '    }', ...
    '  });', ...
    % A page is rebuilt whenever its document is - docking a figure moves it
    % into the desktop's document, which reloads it - while the engine keeps
    % the state. Take what is already there; only ask for a fresh start when
    % there is nothing, so a well the user reshaped is not reset behind them.
    '  adopt(htmlComponent.Data);', ...
    '  if (!st) { htmlComponent.sendEventToNelson("ready", {}); }', ...
    '}'}, newline());
end
%=============================================================================
